{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Свободное место на файловой системе",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"nodeexporter_mac_os\", mountpoint=\"/\"}",
     "legendFormat": "mac os"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=\"nodeexporter_docker\", mountpoint=\"/\"}",
     "legendFormat": "docker "
    }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes {instance=\"nodeexporter_docker\"}",
     "legendFormat": "docker"
    },
    {
     "expr": "node_memory_inactive_bytes {instance=\"nodeexporter_mac_os\"} ",
     "legendFormat": "mac os"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1" },
    { "expr": "node_load5", "legendFormat": "5" },
    { "expr": "node_load15", "legendFormat": "15" }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"nodeexporter_docker\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "docker"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"nodeexporter_mac_os\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "mac os"
    }
   ]
  }
 ]
}