global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          instance: 'nodeexporter_docker'

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:9100']
      labels:
        instance: 'nodeexporter_mac_os'
