version: '3'

services:
  clickhouse:
    image: centos:7
    container_name: hw_8_2_clickhouse
    tty: true
    command: /bin/bash -c "exec /bin/bash"

  #
  #command: >
  #  /bin/bash -c " yum -y update &&  yum install -y gcc openssl-devel bzip2-devel libffi-devel make wget && wget -P /root https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tgz && tar zxvf /root/Python-3.10.13.tgz -C /root/ && cd /root/Python-3.10.13 && ./configure --enable-optimizations && make altinstall && ln -sfn /usr/local/bin/python3.10 /usr/bin/python3.10 && ln -sfn /usr/local/bin/pip3.10 /usr/bin/pip3.10 && exec /bin/bash"
  # command: /bin/bash -c "yum -y update && yum install -y python3.10 && exec /bin/bash"

  vector:
    image: ubuntu
    container_name: hw_8_2_vector
    tty: true
    command: /bin/bash -c "exec /bin/bash"
    #command: /bin/bash -c "apt-get -y update && exec /bin/bash"
    #command: /bin/bash -c "apt-get -y update && apt-get -y install sudo && apt-get install -y python2.7 && exec /bin/bash"
