---
clickhouse:
  hosts:
    hw_8_2_clickhouse:
      ansible_python_interpreter: /usr/bin/python2.7
      #ansible_connection: docker
      ansible_host: 158.160.99.7
      ansible_user: ansible

vector:
  hosts:
    hw_8_2_vector:
      ansible_python_interpreter: /usr/bin/python3
      ansible_host: 158.160.126.205
      ansible_user: ansible
      # ansible_connection: docker

# Группируем дистрибутивы для удобства установки пакетов
red_hat_based_distribs:
  hosts:
    hw_8_2_clickhouse:

debian_based_distribs:
  hosts:
    hw_8_2_vector:
