---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.106.172
    nexus-01:
      ansible_host: 158.160.101.82
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ansible
