- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Проверка валидности конфигурации Vector
      ansible.builtin.command: vector validate
      register: vector_validate
      changed_when: false

    - name: Утверждение, что конфигурация Vector валидна
      ansible.builtin.assert:
        that:
          - vector_validate.rc == 0
        fail_msg: "Конфигурация Vector невалидна"
        success_msg: "Конфигурация Vector валидна"

    - name: Получение статуса сервиса Vector
      ansible.builtin.systemd:
        name: vector
        state: started
      register: vector_service
      changed_when: false

    - name: Утверждение, что Vector успешно запущен
      ansible.builtin.assert:
        that:
          - vector_service.status.ActiveState == 'active'
        fail_msg: "Сервис Vector не запущен"
        success_msg: "Сервис Vector успешно запущен"
