---
# dependency:
#   enabled: true
#   name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
  yamlint .
platforms:
  - name: centos8
    image: docker.io/pycontribs/centosQWE:8
    pre_build_image: true
  # - name: ubuntu
  #   image: docker.io/pycontribs/ubuntu:latest
  #   pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
  # you might want to add your own variables here based on what provisioning
  # you are doing like:
  # image: quay.io/centos/centos:stream8
