---
clickhouse:
  hosts:
    hw_8_2_clickhouse:
      ansible_python_interpreter: /usr/bin/python2.7
      #ansible_connection: docker
      ansible_host: 158.160.58.116
      ansible_user: ansible

vector:
  hosts:
    hw_8_2_vector:
      ansible_python_interpreter: /usr/bin/python3
      ansible_host: 158.160.123.208
      ansible_user: ansible

lighthouse:
  hosts:
    hw_8_2_lighthouse:
      ansible_python_interpreter: /usr/bin/python3
      ansible_host: 51.250.11.74
      ansible_user: ansible

# Группируем дистрибутивы для удобства установки пакетов
red_hat_based_distribs:
  hosts:
    hw_8_2_clickhouse:

debian_based_distribs:
  hosts:
    hw_8_2_vector:
    hw_8_2_lighthouse:
